import type { GameStat, GameStatBlock, Position } from '../domain/player';
import { ALL_GAME_STATS } from '../domain/player';

export const OVR_WEIGHTS: Readonly<Record<Position, Readonly<Record<GameStat, number>>>> = {
  GK: {
    pace: 0,
    finishing: 0,
    passing: 0.1,
    dribbling: 0,
    defending: 0,
    heading: 0.05,
    vision: 0.05,
    physicality: 0.1,
    technique: 0.05,
    handling: 0.3,
    reflexes: 0.25,
    kicking: 0.1,
  },
  'DEF-CB': {
    pace: 0.08,
    finishing: 0.03,
    passing: 0.1,
    dribbling: 0.04,
    defending: 0.25,
    heading: 0.2,
    vision: 0.07,
    physicality: 0.15,
    technique: 0.08,
    handling: 0,
    reflexes: 0,
    kicking: 0,
  },
  'DEF-LB': {
    pace: 0.2,
    finishing: 0.05,
    passing: 0.15,
    dribbling: 0.1,
    defending: 0.2,
    heading: 0.05,
    vision: 0.05,
    physicality: 0.1,
    technique: 0.1,
    handling: 0,
    reflexes: 0,
    kicking: 0,
  },
  'DEF-RB': {
    pace: 0.2,
    finishing: 0.05,
    passing: 0.15,
    dribbling: 0.1,
    defending: 0.2,
    heading: 0.05,
    vision: 0.05,
    physicality: 0.1,
    technique: 0.1,
    handling: 0,
    reflexes: 0,
    kicking: 0,
  },
  'MID-CDM': {
    pace: 0.05,
    finishing: 0.05,
    passing: 0.2,
    dribbling: 0.08,
    defending: 0.2,
    heading: 0.07,
    vision: 0.15,
    physicality: 0.12,
    technique: 0.08,
    handling: 0,
    reflexes: 0,
    kicking: 0,
  },
  'MID-CM': {
    pace: 0.05,
    finishing: 0.1,
    passing: 0.25,
    dribbling: 0.1,
    defending: 0.1,
    heading: 0.05,
    vision: 0.2,
    physicality: 0.05,
    technique: 0.1,
    handling: 0,
    reflexes: 0,
    kicking: 0,
  },
  'MID-CAM': {
    pace: 0.1,
    finishing: 0.15,
    passing: 0.2,
    dribbling: 0.15,
    defending: 0.03,
    heading: 0.02,
    vision: 0.2,
    physicality: 0.05,
    technique: 0.1,
    handling: 0,
    reflexes: 0,
    kicking: 0,
  },
  'MID-LM': {
    pace: 0.2,
    finishing: 0.08,
    passing: 0.15,
    dribbling: 0.15,
    defending: 0.1,
    heading: 0.05,
    vision: 0.1,
    physicality: 0.07,
    technique: 0.1,
    handling: 0,
    reflexes: 0,
    kicking: 0,
  },
  'MID-RM': {
    pace: 0.2,
    finishing: 0.08,
    passing: 0.15,
    dribbling: 0.15,
    defending: 0.1,
    heading: 0.05,
    vision: 0.1,
    physicality: 0.07,
    technique: 0.1,
    handling: 0,
    reflexes: 0,
    kicking: 0,
  },
  'FWD-LW': {
    pace: 0.25,
    finishing: 0.15,
    passing: 0.1,
    dribbling: 0.2,
    defending: 0.02,
    heading: 0.03,
    vision: 0.1,
    physicality: 0.05,
    technique: 0.1,
    handling: 0,
    reflexes: 0,
    kicking: 0,
  },
  'FWD-RW': {
    pace: 0.25,
    finishing: 0.15,
    passing: 0.1,
    dribbling: 0.2,
    defending: 0.02,
    heading: 0.03,
    vision: 0.1,
    physicality: 0.05,
    technique: 0.1,
    handling: 0,
    reflexes: 0,
    kicking: 0,
  },
  'FWD-ST': {
    pace: 0.18,
    finishing: 0.3,
    passing: 0.05,
    dribbling: 0.15,
    defending: 0.02,
    heading: 0.1,
    vision: 0.05,
    physicality: 0.08,
    technique: 0.07,
    handling: 0,
    reflexes: 0,
    kicking: 0,
  },
};

export function computeOvr(position: Position, stats: GameStatBlock): number {
  const weights = OVR_WEIGHTS[position];
  let total = 0;
  for (const stat of ALL_GAME_STATS) {
    total += stats[stat] * weights[stat];
  }
  return Math.round(total);
}

export function clampStat(value: number): number {
  if (Number.isNaN(value)) return 0;
  return Math.max(0, Math.min(100, Math.round(value)));
}

export function defaultStatBlock(): GameStatBlock {
  return {
    pace: 50,
    finishing: 50,
    passing: 50,
    dribbling: 50,
    defending: 50,
    heading: 50,
    vision: 50,
    physicality: 50,
    technique: 50,
    handling: 50,
    reflexes: 50,
    kicking: 50,
  };
}
